#!/usr/bin/env bash
# File: shoot
# Author: Yegor Bayev <baev.egor (at) gmail.com>
# Derived from http://sirupsen.com/static/misc/shoot by Sirupsen @ http://sirupsen.dk
#
# Description: Very simple script to make you
# select a region of your screen, which will be captured, and
# then uploaded. The URL will then be injected into your clipboard.
#
# Dependencies: curl, scrot, xclip, libnotify-bin
#
# License:
#
# Copyright 2013 Yegor Bayev <baev.egor (at) gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see [http://www.gnu.org/licenses/].

CMDLIST="scrot xclip curl notify-send"
for e in $CMDLIST; do
    if [ -z "$(which $e)" ]; then
        echo "$e not installed, quit."
        exit 1
    fi
done

SHOTPATH="$HOME/shot.png"

function uploadImage {
    curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
}

if scrot -s $SHOTPATH; then
    LINK=$(uploadImage $SHOTPATH) 
    echo $LINK | xclip -selection c
    rm $SHOTPATH
    notify-send "Screenshot on $LINK"
fi

# shoot ends here
